### ISSUE TITLE
Crash on Re-Load of Mining Dimension on Game Startup when Avatar was in mining dimension on leaving

### ISSUE THREAD

**Issue by Knito58** [Draylar/miners_horizon#9]
Don't know exactly how to describe the problem in a header. What happened:
I left the game when I was in the mining dimension. When loading the save game the other day then the game crashes just after  the "100%" rectangle when the world should show up.
Other saves do work, it is just the one where I left in the mining dimension.

**Comment by Knito58** [comment]
https://pastebin.com/J9kUy6Tn

**Comment by Draylar** [comment]
Fixed in 0ad2805. Thank you!

**Comment by Knito58** [comment]
1.4.1: Not fixed jet. As before, other saves do work, just the one with the "quitting in mining dimension" kills the game with a crash.
https://pastebin.com/sAFBJFfx

**Comment by Boredhermit** [comment]
I having the same issue, Just installed this mod this morning. My version Minecraft is 1.41.1 My version of the mod is 1.4.1

**Comment by Boredhermit** [comment]
https://pastebin.com/sFVBXj9X

**Comment by Draylar** [comment]
Are you on a server? Can you go into your saves folder and delete the Miner's Horizon world folder, as well as the config file (assuming it's from an older version and needs to be re-built) and then try to re-join?

I just started the game up in Fabric 1.14.1 with API 3 and tried the following things:
 - logging in and out
 - fully closing game and logging in an out
 - deleting the dimension while I'm still in it and relogging

I did not crash. This was on a client, so it may be different on a server.

I know what the issue is but I'm not sure how to reproduce it reliably.

**Comment by Boredhermit** [comment]
I'm not on a server, do you want me to delete "DIM_miners_horizon" folder in my world save folder?

**Comment by Draylar** [comment]
Yeah. Also, delete the minershorizon.json file in your config folder.

**Comment by Boredhermit** [comment]
After I deleted those two things.
The game crashed whilst ticking memory connection
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 5/22/19 2:04 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at net.minecraft.class_3324.method_14570(class_3324.java:136)
	at net.minecraft.class_3248.method_14384(class_3248.java:111)
	at net.minecraft.class_3248.method_18785(class_3248.java:63)
	at net.minecraft.class_2535.method_10754(class_2535.java:239)
	at net.minecraft.class_3242.method_14357(class_3242.java:171)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:842)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:764)
	at net.minecraft.class_1132.method_3748(class_1132.java:128)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3324.method_14570(class_3324.java:136)
	at net.minecraft.class_3248.method_14384(class_3248.java:111)
	at net.minecraft.class_3248.method_18785(class_3248.java:63)
	at net.minecraft.class_2535.method_10754(class_2535.java:239)

-- Ticking connection --
Details:
	Connection: net.minecraft.class_2535@2bd21eb2
Stacktrace:
	at net.minecraft.class_3242.method_14357(class_3242.java:171)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:842)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:764)
	at net.minecraft.class_1132.method_3748(class_1132.java:128)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1160062800 bytes (1106 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1: Auto Config v1 1.1.2+mc1.14.1
		cloth-config: Cloth Config 0.2.1+build.14
		fabric: Fabric API 0.3.0-pre+build.157a
		fabric-api-base: fabric-api-base 0.1.0+f1618918
		fabric-commands-v0: fabric-commands-v0 0.1.0+f1618918
		fabric-containers-v0: fabric-containers-v0 0.1.0+f1618918
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+45e1a1c8
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+f1618918
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+f1618918
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+9232ac87
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+f1618918
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.0+f1618918
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+f1618918
		fabric-models-v0: fabric-models-v0 0.1.0+f1618918
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.0+f1618918
		fabric-networking-v0: fabric-networking-v0 0.1.1+57f0d19c
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.0+9232ac87
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.1.0+f1618918
		fabric-rendering-v0: fabric-rendering-v0 0.1.0+f1618918
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.0+f1618918
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.0+f1618918
		fabric-textures-v0: fabric-textures-v0 0.1.0+f1618918
		fabricloader: Fabric Loader 0.4.7+build.147
		miners_horizon: Miner's Horizon 1.4.1
		modmenu: Mod Menu 1.5.4-85
		voxelmap: VoxelMap 1.9.2
	Player Count: 0 / 8; []
	Data Packs: fabric/fabric-mining-levels-v0, vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by Draylar** [comment]
I've tried everything and I can't reproduce this. I went from 1.3.1 to 1.4.0 to 1.4.1 in the same singleplayer world and I never got it to crash. If you just installed 1.4.1 this morning on the client there should be no issue-- I'm guessing it only crashes when the stars align from previously failing versions. I'm going to ask around and see if other people can reproduce it. I will get back to you shortly.

**Comment by Boredhermit** [comment]
OK, thanks. If you need me to do any more testing I can. I have not tried this on a new world. I really don't want to start over.

**Comment by Draylar** [comment]
Could you send me the world save file? Zip it up and attach it here.

**Comment by Boredhermit** [comment]
Do you have somewhere else I can send it to? It wont let me attach anything bigger than 10 megs on here, with max compression its still 34megs, I guess I could split it up if you could put it back together.

**Comment by Draylar** [comment]
The two options I can think of are dropbox or a git repo. Should be easy to just create a new repository on this site and upload the jar to it.

If I have the jar, I can attempt to reproduce the issue and also fix your save so your player just spawns in the overworld.

**Comment by Boredhermit** [comment]
Try this link and see if this is what you need.
https://www.dropbox.com/sh/gq2te2ti40rfgpv/AACiykmNDgxcN9cEQJO0dk8_a?dl=0

**Comment by Draylar** [comment]
Yeah, that's _definitely_ crashing. Thanks much.

**Comment by Draylar** [comment]
Boredhermit & Knito, can you try this new version on the worlds that are crashing? It should put your character at world spawn (in the Overworld) and fix the NBT issues. Seems like this was a one-off thing that probably only hit the two of you, and maybe a couple of others at most. 

Note that this is a zipped jar, so unzip it before adding it to your mods folder.
[miners-horizon-1.4.2.zip](https://github.com/Draylar/miners_horizon/files/3209747/miners-horizon-1.4.2.zip)

**Comment by Boredhermit** [comment]
Thank you so much for fixing my save, it's works!!!!!!  There is something I noticed,after I got back to my house from my spawn point,I slept in a bed, went to the miner dimension. I did "save and quit" when I reloaded it put back at the spot you reset my spawn......  I dont know if that was intentional or not, just thought you should know.

**Comment by Draylar** [comment]
ugh, figured something like that would happen. Might be worth leaving the mining dimension, removing the Miner's Horizon jar & world file, re-loading into the world, (exiting) reading the jar, and re-joining back into the world. I haven't pushed this jar to CurseForge yet so I'll try to look for a solution to that as well.

**Comment by Knito58** [comment]
Thank you for the test file. It does not crash but takes me back near my world spawn point in the overworld. The saved game is rescued! 
Thank you very much for helping me with that. In the next days I will take care on leaving the game in the overworld only.
:)

**Comment by Draylar** [comment]
_Should_ be fully fixed in the 1.5.0 release (no more weird spawn mechanics, either).
